# Generated by Django 4.0.5 on 2022-06-23 10:42

import app1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_customer_username_alter_invitecode_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('content', models.FileField(blank=True, default=app1.models.get_default_profile_image, null=True, upload_to='contentprofiles/')),
                ('is_block', models.BooleanField(default=False, null=True)),
                ('is_special', models.BooleanField(default=False, null=True)),
                ('is_promoted', models.BooleanField(default=False, null=True)),
                ('is_highdemand', models.BooleanField(default=False, null=True)),
                ('num_of_comments', models.PositiveIntegerField(default=0, null=True)),
                ('is_private', models.BooleanField(default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.customer')),
                ('likers', models.ManyToManyField(related_name='content_liked', to='app1.customer')),
            ],
        ),
    ]
