# Generated by Django 4.0.5 on 2022-06-23 18:13

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.ImageField(blank=True, default=app1.models.get_default_profile_image, null=True, upload_to='contentprofiles/'),
        ),
    ]
