# Generated by Django 4.0.5 on 2022-06-26 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='watch',
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='watch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.file'),
        ),
    ]
