# Generated by Django 4.0.5 on 2022-06-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_watchhistory_created_date_remove_watchhistory_watch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchhistory',
            old_name='created_date',
            new_name='last_viewed',
        ),
    ]
