# Generated by Django 4.0.5 on 2022-06-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(related_name='tagsadded', to='app1.tag'),
        ),
    ]
