# Generated by Django 4.0.5 on 2022-07-06 15:57

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_file_views_tag_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(blank=True, default=app1.models.get_default_profile_image, null=True, upload_to=''),
        ),
    ]
