# Generated by Django 4.0.5 on 2022-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_file_imagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_owner',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
