# Generated by Django 4.0.5 on 2022-07-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_invitecode_is_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_vid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='is_restricted',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
