# Generated by Django 4.0.5 on 2022-07-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_file_is_vid_alter_invitecode_is_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_vid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
