# Generated by Django 4.0.5 on 2022-07-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_forgotpasswordrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordrequest',
            name='hisemail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
