# Generated by Django 4.0.5 on 2022-06-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_blocked',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
