# Generated by Django 4.0.5 on 2022-06-26 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.customer')),
                ('watch', models.ManyToManyField(null=True, related_name='file', to='app1.file')),
            ],
        ),
    ]
