# Generated by Django 4.0.5 on 2022-07-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_tag_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
