# Generated by Django 4.0.5 on 2022-07-06 15:59

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='imagefile',
            field=models.ImageField(blank=True, default=app1.models.get_default_profile_image, null=True, upload_to=''),
        ),
    ]
