# Generated by Django 4.0.5 on 2022-07-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_forgotpasswordrequest_hisemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
                ('safefile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.file')),
            ],
        ),
    ]
